---
# algorithm_param:

optimizer_config:
  class: "torch.optim.Adam"
  lr: 0.01

model_config:
  upper: 5
  lower: -5
  init_noise: 30
  shift: 2
  independent: False



# experiment:
experiment_config:
  sample_size: 1000
  seed: 2023


# independent
# test_function