---
# algorithm_param:
N: [1, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
# m: [1, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
alpha: [0]
alpha_inc: [0.1, 1]

naive: False
lr: 0.01
momentum: 0


# test_function:
shift: 2

# experiment:
sample_size: 10000
seed: 2023


# independent
# test_function