---
# algorithm_param:
N: 25

alpha: 0
alpha_inc: 0.01
# If set rv to be true, set alpha_inc to be 0.01, otherwise, 0.1
rv: True

lr: 0.01
momentum: 0

# test_function:
shift: 4

# experiment:
sample_size: 10
seed: 2023


# independent
# test_function