#!/bin/bash
args=''
for i in "$@"; do
  i="${i//\\/\\\\}"
  args="$args \"${i//\"/\\\"}\""
done

singularity exec --overlay ~/zc2157/overlay-50G-10M.ext3:ro /scratch/work/public/singularity/cuda11.6.124-cudnn8.4.0.27-devel-ubuntu20.04.4.sif /bin/bash -c "
source /ext3/env.sh;
conda activate torch;
python3 $args
"